// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCRMyyh5I7zQILBDsMTZSY9cWCeNf-Z4',
    appId: '1:333941493755:web:106b4cec1fd148660c055e',
    messagingSenderId: '333941493755',
    projectId: 'jihc-lostandfound-hosting',
    authDomain: 'jihc-lostandfound-hosting.firebaseapp.com',
    storageBucket: 'jihc-lostandfound-hosting.firebasestorage.app',
    measurementId: 'G-TPMSVYGV9J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRM1l9zKnAHkJBbwFW4D7lLEhGZOeh_aM',
    appId: '1:333941493755:ios:9bfb66a3262554540c055e',
    messagingSenderId: '333941493755',
    projectId: 'jihc-lostandfound-hosting',
    storageBucket: 'jihc-lostandfound-hosting.firebasestorage.app',
    iosBundleId: 'com.example.jihcLandf',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1o_ht2stt1JTjiL3MyzvEysAmNglTO0',
    appId: '1:333941493755:android:8092508c492445040c055e',
    messagingSenderId: '333941493755',
    projectId: 'jihc-lostandfound-hosting',
    storageBucket: 'jihc-lostandfound-hosting.firebasestorage.app',
  );

}