// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOeOXkJkPTvx62YPL1QfTUIfBVfk_YLM',
    appId: '1:553625297259:web:8646e54888b35fd1262c2e',
    messagingSenderId: '553625297259',
    projectId: 'jihc-lostandfound',
    authDomain: 'jihc-lostandfound.firebaseapp.com',
    storageBucket: 'jihc-lostandfound.firebasestorage.app',
    measurementId: 'G-G1X1C25D5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmprFkdbRm6fCGboUw9l6ijrpbj8IfW0g',
    appId: '1:946407130811:android:db22bff35f80ab30864b9e',
    messagingSenderId: '946407130811',
    projectId: 'jihclostandfound',
    storageBucket: 'jihclostandfound.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9lVSaTS7ALSjEft3_AnzaVMenD61oB1Q',
    appId: '1:946407130811:ios:9300eab22fb4e5d4864b9e',
    messagingSenderId: '946407130811',
    projectId: 'jihclostandfound',
    storageBucket: 'jihclostandfound.firebasestorage.app',
    iosBundleId: 'com.example.jihcLandf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9lVSaTS7ALSjEft3_AnzaVMenD61oB1Q',
    appId: '1:946407130811:ios:9300eab22fb4e5d4864b9e',
    messagingSenderId: '946407130811',
    projectId: 'jihclostandfound',
    storageBucket: 'jihclostandfound.firebasestorage.app',
    iosBundleId: 'com.example.jihcLandf',
  );

}